---
title: "Investigating styler"
author: "Lorenz Walthert"
date: "1/18/2018"
output: html_document
---

Parsing the git repo and add line history
```{r}
library(gitsum)
library(magrittr)
library(tidyr)
library(dplyr)
library(ggplot2)
remove_gitsum()
init_gitsum()
lines <- parse_log_detailed() %>%
  unnest() %>%
  #filter(grepl("colwise", .data$changed_file)) %>%
  set_changed_file_to_latest_name() %>%
  add_line_history()
```

Filter out the files that were changed more than 80 times.
```{r}
r_files <- grep("^R/", lines$changed_file, value = TRUE)

to_plot <- lines %>%
  filter(changed_file %in% r_files) %>%
  add_n_times_changed_file() %>%
  filter(n_times_changed_file > 6)

ggplot(to_plot, aes(x = date, y = current_lines)) + 
  geom_step() + 
  scale_y_continuous(name = "Number of Lines", limits = c(0, NA)) + 
  facet_wrap(~changed_file, scales = "free_y")

```

Filter the last commit of every file to compare the line stats
```{r}
lst_commit_by_file <- lines %>%
  ungroup() %>%
  group_by(changed_file) %>%
  arrange(desc(date)) %>%
  slice(1)
View(lst_commit_by_file)

```


Generate the file stats from the true data
```{r}
system("find . -name '*.R' | xargs wc -l > file-lines.txt")
system("find . -name '*.r' | xargs wc -l >> file-lines.txt")
```

Merge them
```{r}
library(gitsum)
library(tidyverse)
file_stats <- readr::read_csv(file = "file-lines.txt", col_names = FALSE) %>%
  transmute(file = trimws(X1)) %>%
  separate(file, into = c("current_lines_true", "changed_file"), sep = " ", remove = TRUE) %>%
  mutate(changed_file = stringr::str_sub(.data$changed_file, 3))

joined <- left_join(lst_commit_by_file, file_stats) %>%
  ungroup() 


joined %>%
  summarize(share_of_true_line_detections = 
      mean((.data$current_lines == .data$current_lines_true), na.rm = TRUE)
  )

joined %>%
  filter(grepl("\\.r$", .data$changed_file, ignore.case = TRUE)) %>%
  View()

```

# Investigate the problems
We identified a file where the stats are not identical. Let's find out more about
it.
```{r}
joined %>%
  filter(current_lines != current_lines_true) %>% View()


relevant_range <- range(which(lines$hash %in% c("9bc41062154411e66a88662d61293559c218c03c", "fdf6c5eb3d0550d149c63cdcd4ace061d8d5a264")))
lines %>%
  ungroup() %>%
  slice(seq(relevant_range[1], relevant_range[2], by = 1)) %>%
  filter(changed_file == "tests/testthat/test-colwise.R")
  arrange(global_date) %>% View()
```


```{r}
lines %>%
  filter(changed_file == "tests/testthat/test-colwise-mutate.R")

lines %>%
  filter(message == "Move colwise mutate in own file")

lines %>%
  filter(message == "Move database related code to dbplyr")
```

